// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAckJCz4OrVoYr5C1tsssmhKC19iY-D9XY',
    appId: '1:848490235129:web:adfe9c1b68cb058942ce28',
    messagingSenderId: '848490235129',
    projectId: 'prakflutterfirebase-7dff7',
    authDomain: 'prakflutterfirebase-7dff7.firebaseapp.com',
    databaseURL: 'https://prakflutterfirebase-7dff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prakflutterfirebase-7dff7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLlUIPgaeIPRIMak2doZmvw81iQZeGgR8',
    appId: '1:848490235129:android:9ef1eb11f89172a842ce28',
    messagingSenderId: '848490235129',
    projectId: 'prakflutterfirebase-7dff7',
    databaseURL: 'https://prakflutterfirebase-7dff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prakflutterfirebase-7dff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCljKlssbKPwl6-EZ4oNrZMTrAMPZZ6WfE',
    appId: '1:848490235129:ios:df8c49736f5f040a42ce28',
    messagingSenderId: '848490235129',
    projectId: 'prakflutterfirebase-7dff7',
    databaseURL: 'https://prakflutterfirebase-7dff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prakflutterfirebase-7dff7.appspot.com',
    iosClientId: '848490235129-kjb8cgpvr4iqh0dlg1fbq41macpi0ik7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCljKlssbKPwl6-EZ4oNrZMTrAMPZZ6WfE',
    appId: '1:848490235129:ios:df8c49736f5f040a42ce28',
    messagingSenderId: '848490235129',
    projectId: 'prakflutterfirebase-7dff7',
    databaseURL: 'https://prakflutterfirebase-7dff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prakflutterfirebase-7dff7.appspot.com',
    iosClientId: '848490235129-kjb8cgpvr4iqh0dlg1fbq41macpi0ik7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAckJCz4OrVoYr5C1tsssmhKC19iY-D9XY',
    appId: '1:848490235129:web:9dbacc265c8bdc6d42ce28',
    messagingSenderId: '848490235129',
    projectId: 'prakflutterfirebase-7dff7',
    authDomain: 'prakflutterfirebase-7dff7.firebaseapp.com',
    databaseURL: 'https://prakflutterfirebase-7dff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prakflutterfirebase-7dff7.appspot.com',
  );
}
